app_forum/urls.py
from django.conf.urls import url

from .views import index, get_forum_posts, post_forum

urlpatterns = [
    url(r'^$', index, name="index"),
    url(r'^get-forum-posts/$', get_forum_posts, name="get-forum-posts"),
    url(r'^post-forum/$', post_forum, name="post-forum"),
]

app_login/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

app_profile/urls.py
from .views import index, load_profile, refresh
from django.conf.urls import url
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^load-profile/$', load_profile, name='load-profile'),
    url(r'^refresh/(?P<id>[-\w]+)/$', refresh, name='refresh'),
]

tugas_2_ppw/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView

import app_login.urls as login
import app_profile.urls as app_profile
import app_forum.urls as app_forum

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app-login/', include(login, namespace = 'app-login')),
    url(r'^forum/', include(app_forum, namespace="forum")),
    url(r'^profile/', include(app_profile,namespace='profile')),
    url(r'^$', RedirectView.as_view(url = '/app-login/', permanent='true'), name='index')
]

app_forum/models.py
from django.db import models
from app_profile.models import Perusahaan

class Forum(models.Model):
	# id as primary-key
	perusahaan = models.ForeignKey(Perusahaan, on_delete=models.CASCADE)
	content = models.CharField(max_length=1000)
	posted_at = models.DateTimeField(auto_now_add=True)

app_login/models.py
from django.db import models

# Create your models here.

app_profile/models.py
from django.db import models

class Perusahaan(models.Model):
    nama_perusahaan = models.CharField(max_length=200)
    tipe_perusahaan = models.CharField(max_length=200)
    web_perusahaan = models.CharField(max_length=200)
    spesialitas_perusahaan = models.CharField(max_length=200)
    pic_perusahaan = models.CharField(default="", max_length=500)

app_forum/forms.py
from django import forms

class Forum_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
	}
	content_attrs = {
		'type': 'text',
		'cols': 100,
		'rows': 10,
		'class': 'todo-form-textarea',
		'placeholder':'Masukkan isi dari forum...'
	}

	content = forms.CharField(label='', required=True, max_length=1000, widget=forms.Textarea(attrs=content_attrs))
	

app_forum/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages

import json
from app_profile.models import Perusahaan
from .models import Forum
from .forms import Forum_Form

response = {"author": "Ahmad Hasan Siregar"}
MAX_FORUM_PER_PAGE = 3
DEFAULT_DATETIME_FORMAT = "%Y-%m-%dT%H:%MZ"

def index(request):
	# TODO-integration: check if a request is logged in
	if "perusahaan_id" not in request.session:
		# TODO-integration: redirect to login page
		# return HttpResponseRedirect(reverse('app-login:index'))
		request.session["perusahaan_id"] = 1

	perusahaan_id = int(request.session["perusahaan_id"])
	response["perusahaan"] = Perusahaan.objects.get(pk=perusahaan_id)
	response["forum_form"] = Forum_Form
	response.update(json.loads(get_forum_posts(request).content.decode("utf-8")))

	html = "app_forum/forum.html"

	print("response index => ", response)
	return render(request, html, response)

# one-indexed page
def get_forum_posts(request):
	if request.method != 'GET' or "perusahaan_id" not in request.session:
		return HttpResponseRedirect(reverse('forum:index'))

	data = {"forums": []}
	page = int(request.GET.get("page", 1))

	# return empty forums
	if page < 1:
		return JsonResponse(data)

	perusahaan_id = int(request.session["perusahaan_id"])
	offset = 3*(page-1)
	query_results = Forum.objects.filter(perusahaan=perusahaan_id)[offset : offset+MAX_FORUM_PER_PAGE]
	
	for forum in query_results:
		data["forums"].append({"id": forum.id, "perusahaan_id" : forum.perusahaan.id, \
			"perusahaan_nama" : forum.perusahaan.nama_perusahaan, "content" : forum.content, \
			"posted_at" : forum.posted_at.strftime(DEFAULT_DATETIME_FORMAT)})

	return JsonResponse(data)

def post_forum(request):
	if request.method == "POST" and "perusahaan_id" in request.session:
		form = Forum_Form(request.POST or None)
		if form.is_valid():
			content = request.POST["content"]
			perusahaan = Perusahaan.objects.get(pk=int(request.session["perusahaan_id"]))
			new_forum = Forum(perusahaan=perusahaan, content=content)
			new_forum.save()


	return HttpResponseRedirect(reverse("forum:index"))

app_login/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages

response = {}

# NOTE : untuk membantu dalam memahami tujuan dari suatu fungsi (def)
# Silahkan jelaskan menggunakan bahasa kalian masing-masing, di bagian atas
# sebelum fungsi tersebut.

# ======================================================================== #
# User Func
# Apa yang dilakukan fungsi INI? #silahkan ganti ini dengan penjelasan kalian 
def index(request):
    print ("#==> masuk index")
    if 'id' in request.session:
        return HttpResponseRedirect(reverse('app-login:profile'))
    else:
        html = 'app_login/app_login.html'
        response['login'] = False
        return render(request, html, response)

def add_session(res, request):
	response['login'] = True
	id = request.POST['id']
	request.session['id'] = id

def profile(request):
    print ("#==> profile")
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('app-login:index'))

    set_data_for_session(response, request)

    html = 'app_login/app_login.html'
    return render(request, html, response)

app_profile/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Perusahaan

response= {}
id_per = ""

# Create your views here.
def index(request):
    html = 'app_profile/session/app_login.html'
    response['status'] = "None"
    print(request);
    return render(request, html, response)

@csrf_exempt
def load_profile(request):
    namaPerusahaan = request.POST['namaPerusahaan']
    headline = request.POST['headline']
    industry = request.POST['industry']
    email = request.POST['email']
    picture = request.POST['picture']
    public = request.POST['public']

    length_perusahaan = Perusahaan.objects.filter(nama_perusahaan = namaPerusahaan).count()
    if length_perusahaan == 0:
        perusahaan = Perusahaan(nama_perusahaan=namaPerusahaan, tipe_perusahaan=industry, web_perusahaan=public, spesialitas_perusahaan=headline, pic_perusahaan=picture)
        perusahaan.save()


    

def refresh(request, id):
    perusahaan = Perusahaan.objects.get(nama_perusahaan= id)
    perusahaan.delete()
    print(perusahaan.nama_perusahaan)
    response = {'name': perusahaan.nama_perusahaan, 'type': perusahaan.tipe_perusahaan, 'web': perusahaan.web_perusahaan, 'spesial': perusahaan.spesialitas_perusahaan, 'pic': perusahaan.pic_perusahaan}
    html = "app_profile/app_profile.html"
    return render(request, html, response)

app_forum/templates/app_forum/forum.html
{% extends "app_forum/layout/base.html" %}

{% block content %}
<section name="forum-list" id="forum-list">
	<div class="container">
        <h2>Forum {{ perusahaan.nama_perusahaan }}</h2>
        <div id="forum-entry-group" class="flex">
            {% if forums %}
                {% for forum in forums %}
                    <div class="flex-item">
                        <div class="forum-list">
                            <div class="forum-list-title">
                                {{ perusahaan.nama_perusahaan }}
                            </div>
                            <div class="forum-list-date-added">
                                {{ forum.posted_at }}
                            </div>
                            <div class="forum-list-description">
                                {{ forum.content }}
                            </div>
                            <div class="forum-list-reply">
                                <div class="forum-list-reply-button" data-id="{{forum.id}}">Reply</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-danger text-center">
                    <strong>Oops!</strong> Belum ada forum diskusi apapun
                </div>
            {% endif %}
        </div>
        <ul class="pagination">
			<li><a class="btn" onClick="prevPage()"><<</a></li>
		    <li class="active"><a id="page-number">1</a></li>
		    <li><a class="btn" onClick="nextPage()">>></a></li>
		</ul>
    </div>
</section>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'forum:post-forum' %}">
            <h2>Input Forum</h2>
            {% csrf_token %}
            {{ forum_form }}
            <input id="submit" type="submit" class="btn btn-lg btn-block btn-info" value="Submit">
            <br>
        </form>
    </div>
</section>
{% endblock %}

{% block javascript %}
<script>
	var pageNumber = 1;

	var nextPage = function() {
		$.ajax({
			method: "GET",
			url: "{% url 'forum:get-forum-posts' %}?page=" + (pageNumber+1),
			dataType: "json",

			success: function(response) {
				if (response.forums.length > 0) {
					pageNumber++;
					$("#page-number").text(pageNumber);
					$(".flex-item").remove();

					response.forums.forEach(function(forum) {
						html = `<div class="flex-item">
	                        <div class="forum-list">
	                            <div class="forum-list-title">` + forum.perusahaan_nama + 
	                            `</div>
	                            <div class="forum-list-date-added">` + forum.posted_at + `</div>
	                            <div class="forum-list-description">` + forum.content + `</div>
	                            <div class="forum-list-reply">
	                                <div class="forum-list-reply-button" data-id="` + forum.id + `">Reply</div>
	                        </div>
	                   </div>`;

	                   $("#forum-entry-group").append(html);
					});
				}
			},

			error: function(response) {
				alert("Gagal mengambil page selanjutnya!");
				console.log(response);
			}
		});
	};

	var prevPage = function() {
		if (pageNumber > 1) {
			$.ajax({
				method: "GET",
				url: "{% url 'forum:get-forum-posts' %}?page=" + (pageNumber-1),
				dataType: "json",

				success: function(response) {
					pageNumber--;
					if (pageNumber < 1) pageNumber = 1;

					$("#page-number").text(pageNumber);
					$(".flex-item").remove();

					response.forums.forEach(function(forum) {
						html = `<div class="flex-item">
	                        <div class="forum-list">
	                            <div class="forum-list-title">` + forum.perusahaan_nama + 
	                            `</div>
	                            <div class="forum-list-date-added">` + forum.posted_at + `</div>
	                            <div class="forum-list-description">` + forum.content + `</div>
	                            <div class="forum-list-reply">
	                                <div class="forum-list-reply-button" data-id="` + forum.id + `">Reply</div>
	                        </div>
	                   </div>`;

	                   $("#forum-entry-group").append(html);
	                });
				},

				error: function(response) {
					alert("Gagal mengambil page sebelumnya!");
					console.log(response);
				}
			});
		}
	};
</script>
{% endblock %}

app_forum/templates/app_forum/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Tugas 1 PPW">
    <meta name="author" content="{{author}}">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> 
    <link rel="shortcut icon" href="http://aux.iconpedia.net/uploads/1755550516208937900.png" />
    <link rel="stylesheet" type="text/css" href="{% static 'app_forum.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <title>Tugas 2 PPW</title>
    <style>
    body{
        background: -webkit-gradient(left top, left bottom, color-stop(12%, rgba(16,127,118,1)), color-stop(50%, rgba(29,150,143,1)), color-stop(94%, rgba(43,176,171,1)), color-stop(100%, rgba(45,180,175,1)));
        background: -webkit-linear-gradient(top, rgba(16,127,118,1) 12%, rgba(29,150,143,1) 50%, rgba(43,176,171,1) 94%, rgba(45,180,175,1) 100%);
        background: -o-linear-gradient(top, rgba(16,127,118,1) 12%, rgba(29,150,143,1) 50%, rgba(43,176,171,1) 94%, rgba(45,180,175,1) 100%);
        background-repeat: no-repeat;
        background-size: cover;
    }
    </style>
</head>
<body>
    <div class="background">
        <header>
            <!-- TODO nama apps kalian -->
            {% include "app_forum/partials/header.html" %}
        </header>
        <content>
            <div class="container">
                {% block content %}
                    <!-- content goes here -->
                {% endblock %}
            </div>

        </content>
        <footer>
            <!-- TODO nama apps kalian -->
            {% block footer %}
            {% include "app_forum/partials/footer.html" %}
            {% endblock %}
        </footer>

        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        {% block javascript %}
        {% endblock %}
    </div>
</body>
</html>

app_forum/templates/app_forum/partials/footer.html
<h1 style="text-align:center; background-color: white">
    <small><em>Made with love by &copy; Class E - Group 4</em></small>
</h1>

app_forum/templates/app_forum/partials/header.html
<style>
  .navbar-brand{
    font-family: 'Press Start 2P', cursive;
    color: green;
    -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
    -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
    -webkit-animation: infinite; /* Safari 4.0 - 8.0 */
    animation-name: example;
    animation-duration: 4s;
  }
  @-webkit-keyframes example {
    from {color: green;}
    to {color: yellow;}
  }

/* Standard syntax */
  @keyframes example {
    from {color: green;}
    to {color: yellow;}
  }

  a{
    font-family: 'Press Start 2P', cursive;
    font-size: 10px  
  }

</style>
<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
<nav class="navbar navbar-light navbar-default navbar-fixed-top" style="background-color:white">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a style ="font:arial;" class="navbar-brand" href=""><b>ENTERPRISE</b></a>
      <a style ="font:arial;" class="navbar-brand" href="{% url 'forum:index' %}"><b>Forum</b></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/profile/"> Profile</a></li>
        <li><a href="/forum/"> Forum</a></li>
        <li><a href="/log-in/"> Log In</a></li>
      </ul>
    </div>
  </div>
</nav>

app_login/templates/app_login/app_login.html
{% extends "app_login/layout/base.html" %}
{% block content %}
<content id="lowongan" class="container">
	<h1 class="rata-tengah judul"><strong>Lowongan Pekerjaan</strong></h1>
	<div class="container lowongan">
		<div class="row">
			<div class="col-sm-8">
				<div class="detail-lowongan panel">
					<h2 class="nama-perusahaan"><b>Buka Hati</b></h2>
					<hr>
					<h3 class="lowongan-perusahaan">Perusahaan Buka Hati membuka lowongan untuk<br>1. Web Development<br>2. Mobile Development</h3>
				</div>
				<div class="col-sm-12">
					<div class="tanggapan-lowongan panel">
						<h4 class="pemberi-tanggapan"><b>Bintang</b></h4>
						<hr>
						<p class="tanggapan">Pak itu digaji ga</p>
					</div>
					<div class="tanggapan-lowongan panel">
						<h4 class="pemberi-tanggapan"><b>Buka Hati</b></h4>
						<hr>
						<p class="tanggapan">1. Web Developer 1000 Juta<br>2. Mobile Developer 1000.00 Juta</p>
					</div>
				</div>

			</div>
		</div>
	</div>
</content>
<!-- sign in with linkedin button -->
<content id="tempat-login">
	<div class="rata-tengah">
		<script type="in/Login"></script>
	</div>
	<div id="button" class="rata-tengah"></div>

</content>

{% endblock %}

app_login/templates/app_login/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Tugas 2 PPW">
    <meta name="author" content="Muhammad Fakhruddin Hafizh">
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"> 
    <link href="{% static 'css/app_login.css' %}" rel="stylesheet">
    <link rel="shortcut icon" href="http://aux.iconpedia.net/uploads/1755550516208937900.png" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
    <link href="https://fonts.googleapis.com/css?family=Archivo+Narrow:700|Julius+Sans+One|Source+Sans+Pro" rel="stylesheet">
    <title>Halaman muka dan Login</title>
    <script type="text/javascript" src="//platform.linkedin.com/in.js">
    api_key:   81n8dfjtuqjfdm
    onLoad:    onLinkedInLoad
    authorize: true
   </script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <style>
    body{
        background: -webkit-gradient(left top, left bottom, color-stop(12%, rgba(16,127,118,1)), color-stop(50%, rgba(29,150,143,1)), color-stop(94%, rgba(43,176,171,1)), color-stop(100%, rgba(45,180,175,1)));
        background: -webkit-linear-gradient(top, rgba(16,127,118,1) 12%, rgba(29,150,143,1) 50%, rgba(43,176,171,1) 94%, rgba(45,180,175,1) 100%);
        background: -o-linear-gradient(top, rgba(16,127,118,1) 12%, rgba(29,150,143,1) 50%, rgba(43,176,171,1) 94%, rgba(45,180,175,1) 100%);
        background-repeat: no-repeat;
        background-size: cover;
    }
    .content{
      margin-top: 70px;
    }
    </style>
</head>
<body>
  <script src="{% static 'js/app_login.js' %}"></script>
    <div class="background">
        <header>
            <!-- TODO nama apps kalian -->
            {% include "app_login/partials/header.html" %}
        </header>
        <content>
            <div class="container content">
                {% block content %}
                    <!-- content goes here -->
                {% endblock %}
            </div>

        </content>
        <footer>
            <!-- TODO nama apps kalian -->
            {% block footer %}
            {% endblock %}
        </footer>

        <!-- Jquery n Bootstrap Script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    </div>
</body>
</html>

app_login/templates/app_login/partials/footer.html
<h1 style="text-align:center; background-color: white">
    <small><em>Made with love by &copy; Class E - Group 4</em></small>
</h1>

app_login/templates/app_login/partials/header.html
<style>
  .navbar-brand{
    font-family: 'Press Start 2P', cursive;
    color: green;
    -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
    -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
    -webkit-animation: infinite; /* Safari 4.0 - 8.0 */
    animation-name: example;
    animation-duration: 4s;
  }
  @-webkit-keyframes example {
    from {color: green;}
    to {color: yellow;}
  }

/* Standard syntax */
  @keyframes example {
    from {color: green;}
    to {color: yellow;}
  }

  a{
    font-family: 'Press Start 2P', cursive;
    font-size: 10px  
  }

</style>
<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
<nav class="navbar navbar-light navbar-default navbar-fixed-top" style="background-color:white">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a style ="font:arial;" class="navbar-brand" href=""><b>ENTERPRISE</b></a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/profile/"> Profile</a></li>
        <li><a href="/forum/"> Forum</a></li>
        <li><a href="/log-in/"> Log In</a></li>
      </ul>
    </div>!-->
  </div>
</nav>

app_profile/templates/app_profile/app_profile.html
<!DOCTYPE html>
{% extends "app_profile/layout/base.html" %}
{% block content %}
<html lang="en">

<style>
	body{
		top:50px;
		position: relative;
		overflow:hidden;
	}
	img{	
	}

	@-webkit-keyframes hvr-pulse-shrink {
    to {
       -webkit-transform: scale(0.9);
       transform: scale(0.9);
	   }
	}
	@keyframes hvr-pulse-shrink {
	  to {
	    -webkit-transform: scale(0.9);
	    transform: scale(0.9);
	  }
	}

	button {
	  display: inline-block;
	  vertical-align: middle;
	  -webkit-transform: perspective(1px) translateZ(0);
	  transform: perspective(1px) translateZ(0);
	  box-shadow: 0 0 1px transparent;
	}
	button:hover, button:focus, button:active {
	  -webkit-animation-name: hvr-pulse-shrink;
	  animation-name: hvr-pulse-shrink;
	  -webkit-animation-duration: 0.3s;
	  animation-duration: 0.3s;
	  -webkit-animation-timing-function: linear;
	  animation-timing-function: linear;
	  -webkit-animation-iteration-count: infinite;
	  animation-iteration-count: infinite;
	  -webkit-animation-direction: alternate;
	  animation-direction: alternate;
	}
	img{
		left:520px;
		top:60px;
		position: relative;
	}
	@-webkit-keyframes typing { from { width: 0; } }
	@-webkit-keyframes blink-caret { 50% { border-color:transparent; } }

	h1 { 
		font-size:30px;
	    font: bold 150% Consolas, Monaco, monospace;
	    border-right: 0.1em solid black;
	    width: 15em; 
	    width: 21ch;
	    margin: 2em 1em;
	    white-space: nowrap;
	    overflow: hidden;
	    -webkit-animation: typing 3s steps(30, end),
	               blink-caret 1s alternate infinite ;
	}

	.profile{
		height: 220px;
		width: 500px;
		position: relative;
		left: 360px;
		top:200px;
		background-color:#FFF8DC;
		border: 1px solid;
        padding: 10px;
        box-shadow: 5px 10px;
        font-style: "Comic Sans MS", cursive, sans-serif;
	}
	.type{
		font-family: 'Press Start 2P', cursive;
		text-align:center
		font-size:5px;
	}
	.spesial{
		font-family: 'Press Start 2P', cursive;
		text-align:center
		font-size:5px;
	}
	.web{
		font-family: 'Press Start 2P', cursive;
		text-align:center
		font-size:5px;
	}
	button{
		font-family: 'Press Start 2P', cursive;
		text-align:center

	}
	h1{
		font-family: 'Press Start 2P', cursive;
	}


</style>
<body>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Press+Start+2P" rel="stylesheet">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<h1 style="font-family: 'Press Start 2P', cursive;">Selamat Datang {{name}}</h1>
	<img src="{{pic}}">
	<button type="button" class="btn" style="position:relative; top:200px; left:270px; font-family:'Press Start 2P', cursive;font-size:12px" href="/log-in/" >Cari Mahasiswa</button>
	<button type="button" class="btn" style="position:relative; top:200px; left:420px; font-family:'Press Start 2P', cursive; font-size:12px" href="/forum/" >Lihat Forum</button>
	<button type="button" class="btn" style="position:relative; top:10px; left:500px; font-family:'Press Start 2P', cursive; font-size:12px" onClick="logout()">Log Out</button>

	<div class = "profile">
		<p class ="type">Tipe Perusahaan    : {{type}}</p>
		<p class= "spesial">Spesialitas        : {{spesial}}</p>
		<p class = "web">Linkedin Perusahaan : {{web}} </p>
	</div>

	<script>
		function logout(){
	    IN.User.logout();
	}
	</script>
	
</body>
{% endblock %}

app_profile/templates/app_profile/partials/footer.html
</br>